# Default values for word-count.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: word-count
  tag: latest
  pullPolicy: IfNotPresent
etcd:
  endpoint: "http://etcd-cluster-client:2379"
gazette:
  endpoint: "http://gazette-gazette:8081"

